---
- hosts: gpunodes
  vars:
    tempFolder: /tmp/tempFolder
  sudo: yes
  remote_user: vagrant
  tasks:
    - name: update system
      apt: update_cache=yes
      apt: upgrade=yes
    - name: create temp folder for installs
      file: path={{ tempFolder }} state=directory

    - include: ldap.yml
    - include: cuda.yml
    - include: adm.yml

    - name: check if a reboot is required
      shell: "[ -f /var/run/reboot-required ]"
      failed_when: False
      register: reboot_required
      changed_when: reboot_required.rc == 0
      notify: restart server
  handlers:
    - name: restart nscd
      service: name=nscd state=restarted
    - name: restart server
      shell: shutdown -r now "Ansible updates triggered"
      async: 0
      poll: 0
      sudo: true
      ignore_errors: true
